Update of the DecayTree structure
JPETTomography/j-pet-framework pull request #261
Opened 2020-09-24 10:01 UTC by kdulski

I copied DecayTree structure from JPetGeant4 to the Framework, in order to be able to analyze simulations done by the new version of the software.

2020-09-24 10:06 UTC, wkrzemien commented on src/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.cpp
> +  while (previousNodeID >= 10) {
What is this 10 number?

2020-09-24 10:07 UTC, wkrzemien commented on src/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.cpp
> +  while (previousNodeID >= 10) {
ok maybe use enum here?

2020-09-24 10:08 UTC, kdulski commented on src/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.cpp
> +  while (previousNodeID >= 10) {
Hits from primary photons have nodeID less than 10, so this is just some boundary that separates primary hits from disturbed hits by some way

2020-09-24 10:09 UTC, kdulski commented on src/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.cpp
> +  while (previousNodeID >= 10) {
Thanks for noticing, probably I would set some variable for that

2020-09-24 10:10 UTC, JPETTomographyTester commented
Found 2 violations:

**Reporter**: cppcheck-matrix-raporter
**Rule**: unmatchedSuppression
**Severity**: INFO
**File**: src/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.cpp L42

Unmatched suppression: unusedFunction

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1371071988>*

**Reporter**: cppcheck-matrix-raporter
**Rule**: unmatchedSuppression
**Severity**: INFO
**File**: src/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.cpp L65

Unmatched suppression: unusedFunction

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1988406391>*

 *<ACCUMULATED-VIOLATIONS>*

2020-09-24 10:10 UTC, wkrzemien commented on include/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.h
> +        std::vector<std::tuple<int, int, int>> fNodeConnections;
This structure is a kind of tree, right?
I

2020-09-24 10:11 UTC, JPETTomographyTester commented
Found 2 violations:

**Reporter**: cppcheck-matrix-raporter
**Rule**: unmatchedSuppression
**Severity**: INFO
**File**: src/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.cpp L42

Unmatched suppression: unusedFunction

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a628217574>*

**Reporter**: cppcheck-matrix-raporter
**Rule**: unmatchedSuppression
**Severity**: INFO
**File**: src/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.cpp L65

Unmatched suppression: unusedFunction

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1245551977>*

 *<ACCUMULATED-VIOLATIONS>*

2020-09-24 10:16 UTC, kdulski commented on include/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.h
> +        std::vector<std::tuple<int, int, int>> fNodeConnections;
Yes, it should be tree-like, previous step can be retracked based on the previousNodeID and connecting track

2020-09-28 06:54 UTC, wkrzemien commented on include/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.h
> +        std::vector<std::tuple<int, int, int>> fNodeConnections;
I was just wondering if it wouldn't be better to use behind it the tree data struct e.g boost has a graph library

2020-09-28 07:09 UTC, alekgajos requested changes
Good work. I am just a little concerned about the logic of `GetPreviousNodeID` (see comment in the code). Otherwise, just one stylistic suggestion.

2020-09-28 09:01 UTC, wkrzemien approved these changes
Nice work. Once you correct  Alek's remarks, I think we can merge it.
Later we can replace it with more efficient data structure

2020-09-28 13:01 UTC, kdulski commented on src/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.cpp
> +      return std::get<1>(fNodeConnections[i]);
There was a mistake, else if should change the value of the previousNodeID as the logic is following
if the nodeId matches some previousNodeId and the track is the same it should return this previousNodeID with priority.

But, if there was a secondary particle track number changes so the second if should cover these cases, where secondary particle was created and for example someone want to go to the primary gamma that generated this particle. The second if should work only for secondaries that is why for the first if value should be returned immediately, but if there were no matching id for the first if, second if should work. I hope that it is more clear now.

2020-09-28 13:01 UTC, kdulski commented on src/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.cpp
> +      return std::get<1>(fNodeConnections[i]);
it was corrected in the new commit

2020-09-28 13:10 UTC, kdulski commented on src/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.cpp
> +    if (std::get<0>(fNodeConnections[i]) == nodeID && std::get<1>(fNodeConnections[i]) != -1
Ok, done in the new commit.
added function for each std::get type
Introducing new variable fPrimaryPreviousNodeID = -1

2020-09-29 14:29 UTC, kdulski commented
I had studied boost::graph and property_tree, but i do not think that these implementation would be useful,
as in simulations two hits could have the same multiplicity and the only way to distinguish them is by the trackID, so
creation new vertex/node would be complicated.

Tomorrow i would propose my implementation of the tree structure that would be better for our simulations.
If you do not merge these PR till tomorrow you could check new version of the decayTree.

2020-10-07 07:00 UTC, wkrzemien commented on include/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.h
> +struct Branch {
It seems nice. My question is could provide a minimum artifical test showing how you construct this tree and read from it. It would be very useful.

2020-10-07 07:00 UTC, wkrzemien commented on include/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.h
> +struct Branch {
E.g. create one tree then add some branches and read from it

2020-10-07 07:02 UTC, wkrzemien commented on include/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.h
> +struct Branch {
The structure of the test you can just copy e.g from
https://github.com/JPETTomography/j-pet-framework/blob/master/tests/Options/JPetOptionsTools/JPetOptionsToolsTest.cpp
or whatever other test

2020-10-11 21:29 UTC, wkrzemien commented on include/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.h
> +struct Branch {
@kdulski I added PR to your PR with the suggested changes

2020-10-14 15:45 UTC, wkrzemien commented on include/GeantParser/JPetGeantDecayTree/JPetGeantDecayTree.h
> +#include <tuple>
tuple is not used anymore, so you can remove it

2020-10-14 15:47 UTC, wkrzemien commented
Looks fine for me. Thanks!

2020-10-16 08:51 UTC, merged