Adding -k option for selecting Unpacker for Barrel/Modular data
JPETTomography/j-pet-framework pull request #274
Opened 2021-01-10 21:42 UTC by kkacprzak

This PR adds a new command line option "-k" for selecting "detector type", that is which Unpacker should be used. Currently available are Unpacker2 for Big Barrel data and Unpacker2D for Modular Layer acquisition. 

"Barrel" option is a default one, so all current functionalities should not be disturbed if "-k" won't be used while running an example.

2021-01-12 12:52 UTC, alekgajos requested changes

2021-01-12 12:52 UTC, alekgajos commented on src/Options/JPetOptionsTools/JPetOptionsTools.cpp
> +    } catch (const std::out_of_range& outOfRangeDetectorTypeException) { }
Should there be no handling of this exception?
E.g. if the user provides a non-existent detector type, the program will default to barrel which is ok, but it would be good to issue a warning about this.

2021-01-12 12:52 UTC, alekgajos commented on tests/Core/JPetCmdParser/JPetCmdParserTest.cpp
> +  auto vectOfFiles =  any_cast<std::vector<std::string>>(result.at("file").value());
Stray space.

2021-01-12 12:52 UTC, alekgajos commented on tests/Core/JPetCmdParser/JPetCmdParserTest.cpp
> +  auto vectOfFiles =  any_cast<std::vector<std::string>>(result.at("file").value());
stray space

2021-01-12 13:00 UTC, alekgajos commented
I am sorry, I failed to enter my general comments along with the above review, so I am posting them as a separate comment:

Besides small remarks to a few places in the code, I have two general concerns that I think we need to fix before merging this PR:
1. First we need a PR to Unpacker2 develop branch bringing Unpacker2D, otherwise the tests will fail to build the framework.
2. Please use the formatting style from our `.clang-format` file in the repository. Otherwise, all feature PR-s will be obfuscated by ubiquitous formatting changes.

2021-01-18 17:21 UTC, kkacprzak reviewed
I added two commits - first with suggested corrections and second with clang formatting.

2021-01-18 17:21 UTC, kkacprzak commented on src/Options/JPetOptionValidator/JPetAdditionalValidators.cpp
> +  if (any_cast<int>(option.second) != 10) {
I have no idea, why this was introduced. BTW, this class isn't used anywhere.

2021-01-18 17:21 UTC, kkacprzak commented on src/Options/JPetOptionsTools/JPetOptionsTools.cpp
> +    } catch (const std::out_of_range& outOfRangeDetectorTypeException) { }
Added error handling here and in getFileType, where it was missing as well

2021-01-19 09:18 UTC, alekgajos commented on include/Tasks/JPetUnpackTask/JPetUnpackTask.h
> +#include "Unpacker2D.h"
Ok, I just merged the PR to Unpacker2 so we are ready in that respect.

2021-01-19 09:19 UTC, alekgajos commented on src/Options/JPetOptionValidator/JPetAdditionalValidators.cpp
> +  if (any_cast<int>(option.second) != 10) {
Thanks, so let us leave it for now and we should discuss removing it as an independent task at the next meeting.

2021-01-19 09:21 UTC, alekgajos commented
retest this please

2021-01-19 11:20 UTC, alekgajos commented
There is still a build error related to missing definition of `outOfRangeOptionException`. Please see the logs from Jenkins or GitHub CI.

2021-01-19 12:07 UTC, kdulski approved these changes
Nice job! I have just three questions. Two in the code and one general:
- Is there a difference in structure of the files from barrel or modular? Because if there is, maybe it would be easier for the user if instead an additional option for running Framework there will be function that will check the structure of the file and use appropriate unpacker? This comment is not for this PR but for future, just as something to think of.

2021-01-23 17:10 UTC, kkacprzak commented on include/Tasks/JPetUnpackTask/JPetUnpackTask.h
> +  int fEventsToProcess = 100000000;
No reason, probably a copy error. Still 10^9 would never be overpassed by a number of time slots in a single file.

2021-01-23 17:11 UTC, kkacprzak commented on src/Tasks/JPetUnpackTask/JPetUnpackTask.cpp
> +    fUnpacker2D->UnpackSingleStep(fInputFile, fInputFilePath, fOutputFilePath, fXMLConfFile, fEventsToProcess, refChannelOffset,
Yes, that's right. New acquisition does not require stretching of trailing edges.

2021-01-23 17:15 UTC, kkacprzak commented
I corrected handling of errors in option tools.

>     * Is there a difference in structure of the files from barrel or modular? 

In general both Unpackers use the same structure of headers and subheaders But the best person to answer this question is Greg, maybe it is feasible to add a method recognizing file structure before reading binary data.

2021-01-25 09:26 UTC, wkrzemien commented on src/Options/JPetOptionsGenerator/JPetOptionsGeneratorTools.cpp
> +                                                                    {"runID", "runID_int"},
I have small doubt about this change, since this changes the option that people are used to it.

2021-01-25 09:30 UTC, wkrzemien commented on include/Tasks/JPetUnpackTask/JPetUnpackTask.h
> +  std::string fOutputFilePath = std::string("");
What is the advantage of writing something like ` std::string fInputFilePath = std::string("");` instead of ` std::string fInputFilePath;` ?

2021-01-25 09:43 UTC, wkrzemien commented on src/Tasks/JPetUnpackTask/JPetUnpackTask.cpp
> +    fUnpacker2 = new Unpacker2();
I think both Unpacker2 and Unpacker2D are used only in the run method, therefore it can become local variables. No need for the class members. Also, I think you don't need to use new to create them in that case,

2021-01-25 09:54 UTC, wkrzemien commented
Nice work

2021-01-27 15:05 UTC, kkacprzak commented on src/Tasks/JPetUnpackTask/JPetUnpackTask.cpp
> +    fUnpacker2 = new Unpacker2();
Yes, you're right, I was following code schema that was already in this class. Changed to local variables.

2021-01-27 15:22 UTC, kkacprzak commented on include/Tasks/JPetUnpackTask/JPetUnpackTask.h
> +  std::string fOutputFilePath = std::string("");
I checked that these strings are initialized before use in the cpp, so there is no need to initialize them in header file.

2021-01-27 15:47 UTC, kkacprzak commented
I committed changes suggested by Wojtek.

2021-01-27 18:11 UTC, alekgajos commented
@wkrzemien @kdulski I understand the PR is ready to merge then?

2021-01-28 10:36 UTC, kdulski commented
@alekgajos From my side, sure.

2021-01-28 10:39 UTC, wkrzemien commented on include/Options/JPetOptionsTools/JPetOptionsTools.h
> +class DetectorTypeChecker
I think, t his should be a namespace detectorTypeCheckek. It has no state, everything is public No need to define a class with static methods.

2021-01-28 10:41 UTC, wkrzemien commented on include/Options/JPetOptionsTools/JPetOptionsTools.h
> +class DetectorTypeChecker
sorry didn't see fstringDeterctorType, but this work as a constant then?

2021-02-02 16:11 UTC, kkacprzak commented on include/Options/JPetOptionsTools/JPetOptionsTools.h
> +class DetectorTypeChecker
DetectorTypeChecker works in the same way as FileTypeChecker, both are included in options namspace. Should I change them both or it can remain like this?

2021-02-03 12:14 UTC, wkrzemien commented on include/Options/JPetOptionsTools/JPetOptionsTools.h
> +class DetectorTypeChecker
I would vote to change the classes into the inner namespaces inside of the jpet_option_tools  eg. DetectorTypeChecker -> `namespace DetectorTypeChecker` or better `namespace detector_type_checks {` 
Ne their of those two are really objects, so constructors, static  etc are not needed if one uses the namespace

2021-02-09 22:36 UTC, wkrzemien approved these changes
Nice work!

2021-02-09 23:29 UTC, kkacprzak commented
Namespace changes submitted.

2021-02-10 09:26 UTC, alekgajos approved these changes

2021-02-10 09:27 UTC, alekgajos commented
retest this please

2021-02-10 09:48 UTC, merged