New Hit Class schema
JPETTomography/j-pet-framework pull request #275
Opened 2021-02-15 23:14 UTC by kkacprzak

This PR adds several classes, according to discussed approach for developing data reconstruction.

2021-03-09 11:31 UTC, alekgajos reviewed
Good job! I just have two doubts to discuss indicated in the comments.

2021-03-09 11:31 UTC, alekgajos commented on include/MC/JPetBaseMCHit/JPetBaseMCHit.h
> +/**
I am not sure if including "base" in the class name is a good idea since it is no longer a base class. Additionally, we should somehow indicate that this is a class intended for the "True" MC.

2021-03-09 11:31 UTC, alekgajos commented on include/MC/JPetBaseMCHit/JPetBaseMCHit.h
> +  MultiplicityTag fMultiplicityTag;
The "genGammaMultiplicity" parameter from J-PET-Geant4 can take a large spectrum of values in case the hits come from scattered photons (11, 12, 13, 21, 23, 23, ..., 101, 102, 103, 201, ...). I think an enum will not work in case of this parameter.

However, I am all for changing the name from "genGammaMultiplicity" so something shorter and more handy as we are using this parameter a lot when discussing MC simulatiions:-)

2021-03-15 07:24 UTC, kkacprzak commented on include/MC/JPetBaseMCHit/JPetBaseMCHit.h
> +/**
I was considering "GenMC" as "generated", but in general all MC is generated by definition. So currently I have no other ideas, how to avoid this "TrueMC" slang

2021-03-15 07:27 UTC, kkacprzak commented on include/MC/JPetBaseMCHit/JPetBaseMCHit.h
> +  MultiplicityTag fMultiplicityTag;
Ok, I will reverse that. I suggest just "Tag" for the new name. "Gamma multiplicity" requires a long explanation anyway, so we can change it to something generic, accompanied with proper documentation.

2021-03-29 08:32 UTC, wkrzemien commented on include/DataObjects/JPetBaseHit/JPetBaseHit.h
> +#ifndef __CINT__
Do we need this __CINT__ flags?

2021-03-29 08:35 UTC, wkrzemien commented on include/DataObjects/JPetBaseHit/JPetBaseHit.h
> +#ifndef __CINT__
I mean i don't know how many people really will use the old ROOT?

2021-03-29 08:36 UTC, wkrzemien commented on include/DataObjects/JPetBaseHit/JPetBaseHit.h
> +  TRef fScin = NULL;
nullptr; ?

2021-03-29 08:47 UTC, wkrzemien commented on include/DataObjects/JPetBaseHit/JPetBaseHit.h
> +  void Clear(Option_t* opt = "");
Is it overridden from  TObject.  Is it automatically called somewhere where we use objects? 
If it is the case, then I would change it to `void Clear(Option_t* ) override;` Without the argument, cause we are not using it anyway. If not, I would change it to `void clear(Option_t* ) override;` but here I don't insist, cause I understand that it already exists like that in `JPetHit`.

2021-03-29 08:52 UTC, wkrzemien commented on include/DataObjects/JPetMCRecoHit/JPetMCRecoHit.h
> +  void Clear(Option_t* opt = "");
See above `void Clear(Option_t* ) override;`

2021-03-29 09:04 UTC, wkrzemien commented on src/DataObjects/JPetRecoHit/JPetRecoHit.cpp
> +void JPetRecoHit::Clear(Option_t*) { fFlag = JPetRecoHit::Unknown; }
Shouldn't we also called the parent Clear method ? e.g.  JPetBaseHit::Clear(); otherwise the orginal fields are not clearead. This probably should be checked accordingly for other cases

2021-03-29 09:13 UTC, wkrzemien commented on include/MC/JPetBaseMCHit/JPetBaseMCHit.h
> +/**
I think either GenMC or TrueMC is better than Base.

2021-03-29 09:17 UTC, wkrzemien commented on include/MC/JPetBaseMCHit/JPetBaseMCHit.h
> +  MultiplicityTag fMultiplicityTag;
Wouldn't be better to call it "HitTag" or "HitType" etc . I don't think that multiplicity is informative at all.

2021-03-29 09:23 UTC, wkrzemien commented on src/MC/JPetBaseMCHit/JPetBaseMCHit.cpp
> +JPetBaseMCHit::MultiplicityTag JPetBaseMCHit::getMultiplicityTag() const { return fMultiplicityTag; }
Wouldn't be nicer to called it `getHitType()` or `getHitTag()`

2021-03-29 09:25 UTC, wkrzemien commented on include/MC/JPetBaseMCHit/JPetBaseMCHit.h
> +  int getMCVtxIndex() const;
Since we are changing it, could you add some comments what given function returns e.g what MCVtxIndex means. One phrase is enough and it would help people to understand it.

2021-03-29 09:28 UTC, wkrzemien requested changes
It looks very nice.
What I would still add (although I don't know exactly in which class) is the paragraph describing the general inheritance tree of hits together with some rationale behind it. It would be very helpful in the future.

2021-04-26 07:28 UTC, wkrzemien commented on include/MC/JPetRawMCHit/JPetRawMCHit.h
> +   * the convention is described in the manual of j-pet-genat4 project
j-pet-geant4

2021-04-26 07:31 UTC, wkrzemien approved these changes
Nice work! I found one typo in the comment that might be fixed.

2021-05-09 08:40 UTC, merged