Towards v10 with Modular
JPETTomography/j-pet-framework pull request #278
Opened 2021-10-04 02:01 UTC by kkacprzak

This PR contains many changes, that aim in incorporating the Modular Detector Analysis approach and updates to data structures. Some changes are in formatting (automated with clang formatted) and unifying the naming conventions. 

Main features:
- store hits in Events, LORs as pointers (JPetBaseHit*) to enable using a variety of Hit classes
- introducing JPetMatrix ParamObjetcs
- restructuring Signals classes to follow a similar strategy as Hits in base/reco inheritance and to refractor to indicate associated ParamObject (JPetChannel -> JPetChannelSignal, JPetPM -> JPetPMSignal, JPetMatrix -> JPetMatrixSignal)
- renaming JPetRawSignal to JPetPMSignal, JPetRecoSignal to JPetShapedSignal, new JPetRecoSignal is inheriting from JPetBaseSingnal and contains reconstruction flags
- adding to JPetScin new fields of rotation (x,y,z) to give a possibility of reconstructing hits in strips not aligned with the z-axis (i.e Trento setup, head-cap in total body design)
- updating GeantParser
- making necessary changes in Scope associated classes
- updating and developing many unit tests

2021-10-04 15:40 UTC, wkrzemien commented on src/GeantParser/JPetGeantParser/JPetGeantParser.cpp
> +double JPetGeantParser::getNextTimeShift()
Any particular reason to change from float to double ?

2021-10-04 15:45 UTC, wkrzemien commented on src/GeantParser/JPetGeantParser/JPetGeantParser.cpp
> +double JPetGeantParser::getNextTimeShift()
It looks like a huge amount of work and a lot of effort. Concerning the review -from my point of view reviewing 170 files changed in one PR is virtually impossible, so I will just go generally over it and leave a comment here and there. Other then that it is beyond my capacity.

2021-10-04 15:47 UTC, wkrzemien commented on src/GeantParser/JPetGeantParser/JPetGeantParser.cpp
> +double JPetGeantParser::getNextTimeShift()
Is there any kind of scheme or the description of the class hierarchy that you are introducing?

2021-10-04 18:11 UTC, wkrzemien commented on src/DataObjects/JPetLOR/JPetLOR.cpp
> +  default:
I know it was like that in the old version, but maybe for default case you could add: `ERROR("Bad index for hitSet is provided " +std::to_string(index));`

2021-11-08 00:51 UTC, JPETTomographyTester commented
Found 1 violations:

**Reporter**: cppcheck-matrix-raporter
**Rule**: unmatchedSuppression
**Severity**: INFO
**File**: /var/jenkins_home/workspace/J-Pet-Framework-matrix-job/boost_version/boost_1_58/cmake/cmake315/gcc/default_gcc/os/ubuntu16/root/root618/src/Core/JPetManager/JPetManager.cpp L121

Unmatched suppression: unusedFunction

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a577067171>*

 *<ACCUMULATED-VIOLATIONS>*

2021-11-08 00:51 UTC, JPETTomographyTester commented
Found 1 violations:

**Reporter**: cppcheck-matrix-raporter
**Rule**: unmatchedSuppression
**Severity**: INFO
**File**: /var/jenkins_home/workspace/J-Pet-Framework-matrix-job/boost_version/boost_1_58/cmake/cmake351/gcc/default_gcc/os/ubuntu16/root/root612/src/Core/JPetManager/JPetManager.cpp L121

Unmatched suppression: unusedFunction

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a517387925>*

 *<ACCUMULATED-VIOLATIONS>*

2021-11-08 01:11 UTC, kkacprzak commented
I have updated tests and files, so now it is ready for review.

2021-11-08 01:11 UTC, kkacprzak commented on src/GeantParser/JPetGeantParser/JPetGeantParser.cpp
> +double JPetGeantParser::getNextTimeShift()
I have posted it on Redmine.

2021-12-05 19:18 UTC, wkrzemien commented on src/DataObjects/Signals/JPetMatrixSignal/JPetMatrixSignal.cpp
> +    ERROR("Cannot add PM sigal with same matrix position as an existing one.");
```suggestion
    ERROR("Cannot add PM signal with same matrix position as an existing one.");
```

2021-12-05 19:52 UTC, wkrzemien commented on include/DataObjects/Signals/JPetPhysSignal/JPetPhysSignal.h
> + * the signal and are needed for further reconstruction of hits. One JPetPhysRignal
```suggestion
 * This class contains the reconstructed physical quantities that characterize
 * the signal and are needed for further reconstruction of hits. One JPetPhysSignal
```

2021-12-05 19:55 UTC, wkrzemien commented on include/GeantParser/JPetGeantParser/JPetGeantParser.h
> +  void fillHistoMCGen(JPetRawMCHit&);
By convention if the name of the argument is not provided, then it can be treated as obsolete

2021-12-05 19:55 UTC, wkrzemien commented on include/GeantParser/JPetGeantParser/JPetGeantParserTools.h
> +  static bool isHitReconstructed(JPetMCRecoHit& hit, const double th);
```suggestion
  static bool isHitReconstructed(const JPetMCRecoHit& hit, const double th);
```

2021-12-05 19:56 UTC, wkrzemien commented on include/GeantParser/JPetGeantScinHits/JPetGeantScinHits.h
> +
I guess those empty lines are not needed

2021-12-05 19:57 UTC, wkrzemien commented on include/ParamObjects/JPetChannel/JPetChannel.h
> +  JPetChannel(int id, int thrNum, double thrVal);
out of curiosty. What is the reason to change float to double precision?

2021-12-05 19:58 UTC, wkrzemien commented on include/ParamObjects/JPetChannel/JPetChannel.h
> +  double fThresholdValue = 0.0;
Do we really need double precision?

2021-12-05 19:59 UTC, wkrzemien commented on include/ParamObjects/JPetLayer/JPetLayer.h
> +  double getRadius() const;
same here, i dont know if we need double precision

2021-12-05 20:03 UTC, wkrzemien requested changes
Very nice and huge work.
I am adding first part of comments. Those are only small things that I spotted so far.
I haven't touched yet the class hierarchy.
One general remark to discuss, do we really want to change float to double? Remember that it is doubling the size of the variable, while in many cases the precision will not be so important

2021-12-28 13:55 UTC, alekgajos requested changes
Great amount of good work!

I just have a few small questions/comments to the code. Besides that, I second Wojtek's suggestion that we should leave the usage of float-s rather than doubles in all the classes that get serialized to ROOT files to avoid their size increasing.

2021-12-28 13:55 UTC, alekgajos commented on tests/Core/JPetManager/JPetManagerTest.cpp
>  /**
What is the reason of these tests being commented out?
Is is because the json setup files used in the tests must be updated?

2021-12-28 13:55 UTC, alekgajos commented on tests/Core/JPetWriter/JPetWriterTest.cpp
> +  std::cout << "Write Tree " << std::flush;
Please remove the cout-s.

2022-02-20 17:24 UTC, kkacprzak commented on src/DataObjects/JPetLOR/JPetLOR.cpp
> +  default:
added

2022-02-20 17:25 UTC, kkacprzak commented on src/DataObjects/Signals/JPetMatrixSignal/JPetMatrixSignal.cpp
> +    ERROR("Cannot add PM sigal with same matrix position as an existing one.");
typo corrected

2022-02-20 17:26 UTC, kkacprzak commented on include/DataObjects/Signals/JPetPhysSignal/JPetPhysSignal.h
> + * the signal and are needed for further reconstruction of hits. One JPetPhysRignal
typo corrected

2022-02-20 17:28 UTC, kkacprzak commented on include/GeantParser/JPetGeantParser/JPetGeantParser.h
> +  void fillHistoMCGen(JPetRawMCHit&);
Ok, I don't know what to do with that, because it is a part of GeantParser logic, my changes only substituted the class of the object.

2022-02-20 17:28 UTC, kkacprzak commented on include/DataObjects/Hits/JPetBaseHit/JPetBaseHit.h
> +  JPetBaseHit(double time, double energy, TVector3& position);
const added

2022-02-20 17:30 UTC, kkacprzak commented on include/GeantParser/JPetGeantScinHits/JPetGeantScinHits.h
> +
empty lines removed

2022-02-20 17:33 UTC, kkacprzak commented on include/ParamObjects/JPetChannel/JPetChannel.h
> +  JPetChannel(int id, int thrNum, double thrVal);
In some classes, it was float, in others double, so I wanted to unify this. But yes, it's better to keep floats.

2022-02-20 17:33 UTC, kkacprzak commented on include/ParamObjects/JPetChannel/JPetChannel.h
> +  double fThresholdValue = 0.0;
Reverted to floats everywhere.

2022-02-20 17:33 UTC, kkacprzak commented on include/ParamObjects/JPetLayer/JPetLayer.h
> +  double getRadius() const;
same

2022-02-20 17:35 UTC, kkacprzak commented on tests/Core/JPetWriter/JPetWriterTest.cpp
> +  std::cout << "Write Tree " << std::flush;
removed

2022-02-20 17:38 UTC, kkacprzak commented on tests/Core/JPetManager/JPetManagerTest.cpp
>  /**
Yes, exactly. We need to prepare updated root and HLD files and revise these tests. And make another PR once the files are on sphinx.

2022-02-20 17:41 UTC, kkacprzak commented on include/ParamObjects/JPetLayer/JPetLayer.h
> +
Well, it was in the param object classes before, so I replicated that in the updated classes. I am not aware if this is needed or used anywhere, but in general, I understand the purpose of this method. 
Shall we keep this or should I remove it from all the class definitions?

2022-02-20 17:44 UTC, kkacprzak commented on include/DataObjects/Signals/JPetPMSignal/JPetPMSignal.h
> +  std::vector<std::pair<JPetChannelSignal, JPetChannelSignal>> fLeadTrailPairs;
Then it shouldn't be reconstructed as a part of the signal - we can't really do anything with this information, so there is no point in storing it. In the signal finder procedure, it would be logged how many missing edges there were (control histogram)

2022-02-20 18:35 UTC, kkacprzak commented on include/MC/JPetMCDecayTree/JPetMCDecayTree.h
> +  int fMCMCDecayTreeIndex = 0;
Changed back to UInt_t

2022-02-20 18:52 UTC, kkacprzak commented on include/DataObjects/JPetHitUtils/JPetHitUtils.h
> -  static double getTimeDiffAtThr(const JPetHit& hit, int threshold);
In my opinion, this method should be moved to the tools class of the reconstruction procedures, as it would have to handle cases separately for PM and SiPMs.

2022-02-21 02:45 UTC, kkacprzak commented
Some requested changes were introduced, some are in need of a discussion.

2022-02-21 02:52 UTC, JPETTomographyTester commented
Found 1 violations:

**Reporter**: cppcheck-matrix-raporter
**Rule**: unmatchedSuppression
**Severity**: INFO
**File**: /var/jenkins_home/workspace/J-Pet-Framework-matrix-job/boost_version/boost_1_58/cmake/cmake315/gcc/default_gcc/os/ubuntu16/root/root618/src/Core/JPetManager/JPetManager.cpp L121

Unmatched suppression: unusedFunction

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a577067171>*

 *<ACCUMULATED-VIOLATIONS>*

2022-02-21 02:52 UTC, JPETTomographyTester commented
Found 1 violations:

**Reporter**: cppcheck-matrix-raporter
**Rule**: unmatchedSuppression
**Severity**: INFO
**File**: /var/jenkins_home/workspace/J-Pet-Framework-matrix-job/boost_version/boost_1_58/cmake/cmake351/gcc/default_gcc/os/ubuntu16/root/root612/src/Core/JPetManager/JPetManager.cpp L121

Unmatched suppression: unusedFunction

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a517387925>*

 *<ACCUMULATED-VIOLATIONS>*

2022-02-21 08:50 UTC, alekgajos commented
> Some requested changes were introduced, some are in need of a discussion.

Thanks! Let's discuss these items at the meeting today.

2022-02-21 08:51 UTC, alekgajos commented on tests/Core/JPetManager/JPetManagerTest.cpp
>  /**
Ok, I agree.

2022-04-04 19:49 UTC, merged